repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. Get the latest from: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
        # Run the linter.
        - id: ruff
          args: [--fix, --exit-non-zero-on-fix]
        # Run the formatter.
        - id: ruff-format